"""
Causal model definitions for the task.
"""

import random
from causalab.causal.causal_model import CausalModel
from .templates import TEMPLATES, fill_template
from .config import TASK_NAME, FOOS, BARS

# TODO: implement variables, values, parents, mechanisms
# the variables "raw_input" and "raw_output" should both be strings
# Some variables are conceptually best expressed as lists or tuples,
# but the causal model implementation requires separating these into
# individual scalar variables with _{i} suffixes (e.g., choice_0, choice_1).
# Avoid creating compound/aggregate variables.
# TODO (human): test to dissuade these meta-variables
variables = ["foo", "bar", "template", "raw_input", "raw_output"]

values = {
    "foo": FOOS,
    "bar": BARS,
    "template": TEMPLATES,
    "raw_input": None,  # Generated from template
    "raw_output": None,  # Generated by model
}

parents = {
    "foo": [],
    "bar": [],
    "template": [],
    "raw_input": ["template", "foo", "bar"],
    "raw_output": ["raw_input"],
}

# TODO: implement other functions for mechanisms
mechanisms = {
    "foo": lambda: random.choice(FOOS),
    "bar": lambda: random.choice(BARS),
    "template": lambda: random.choice(TEMPLATES),
    "raw_input": lambda template, foo, bar: fill_template(template, foo, bar),
    "raw_output": lambda raw_input: "",  # Placeholder - will be filled by model
}

causal_model = CausalModel(variables, values, parents, mechanisms, id=TASK_NAME)
